export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const CHECKOUT_CREATE = 'CHECKOUT_CREATE';
export const CHECKOUT_UPDATE_SHIPPING_ADDRESS = 'CHECKOUT_UPDATE_SHIPPING_ADDRESS';